"""SQLAlchemy declarative Base + auto-discovery of every model module.

Importing this module from `alembic/env.py` causes every file under
`app/models/` to be imported, which registers their classes on
`Base.metadata` so `alembic revision --autogenerate` sees them.

Plan 05 (auth) and Plan 06 (master data) drop new model files into
`app/models/`; they do NOT edit this file. The walk skips `_`-prefixed
modules so internal helpers stay out of the autogen surface.
"""

import importlib
import pkgutil
import pathlib

from sqlalchemy.orm import declarative_base

Base = declarative_base()

# Auto-import every module under app/models/ so Alembic --autogenerate sees them.
_models_dir = pathlib.Path(__file__).resolve().parent.parent / "models"
if _models_dir.exists():
    for _mi in pkgutil.iter_modules([str(_models_dir)]):
        if not _mi.name.startswith("_"):
            importlib.import_module(f"app.models.{_mi.name}")
